//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.DetailSurveys = new HashSet<DetailSurvey>();
        }
    
        public int ID { get; set; }
        public System.DateTime SurveyDate { get; set; }
        public Nullable<int> Departure { get; set; }
        public Nullable<int> Arrival { get; set; }
        public Nullable<int> CabinType { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Subscription { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        public virtual CabinType CabinType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailSurvey> DetailSurveys { get; set; }
    }
}
