//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempt
    {
        public int AttemptId { get; set; }
        public Nullable<int> QnId { get; set; }
        public string UserId { get; set; }
        public string Answer { get; set; }
        public string DateTime { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
