//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionPrice
    {
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public int LevelId { get; set; }
        public int Price { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Level Level { get; set; }
    }
}
