//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchRound
    {
        public int Id { get; set; }
        public int MatchId { get; set; }
        public int RoundNumber { get; set; }
        public int ScoreTeamA { get; set; }
        public int ScoreTeamB { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
