//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.MatchRounds = new HashSet<MatchRound>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public Nullable<int> TeamAId { get; set; }
        public Nullable<int> TeamBId { get; set; }
        public int MatchTypeId { get; set; }
        public int LevelId { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Level Level { get; set; }
        public virtual MatchType MatchType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchRound> MatchRounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
