//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetail
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public string SeatNumber { get; set; }
        public int SeatClassId { get; set; }
    
        public virtual SeatClass SeatClass { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
