//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerTrend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string ItemPurchased { get; set; }
        public string Category { get; set; }
        public Nullable<int> PurchaseAmount { get; set; }
        public string Location { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Season { get; set; }
        public Nullable<decimal> ReviewRating { get; set; }
        public string SubscriptionStatus { get; set; }
        public string ShippingType { get; set; }
        public string DiscountApplied { get; set; }
        public string PromoCodeUsed { get; set; }
        public Nullable<int> PreviousPurchases { get; set; }
        public string PaymentMethod { get; set; }
        public string FrequencyOfPurchases { get; set; }
    }
}
