//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int id { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<bool> isSoftwareCrashed { get; set; }
        public Nullable<System.DateTime> datetime_logout { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
