//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttemptHistory
    {
        public long id { get; set; }
        public long partnerId { get; set; }
        public long SecurityQuesId { get; set; }
        public Nullable<bool> result { get; set; }
        public Nullable<System.DateTime> attemptTime { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
    }
}
