//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path_Partner_Parcel
    {
        public long id { get; set; }
        public Nullable<System.DateTime> deliverTime { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public long parcelId { get; set; }
        public byte[] image { get; set; }
        public long path_partner_id { get; set; }
    
        public virtual Parcel Parcel { get; set; }
        public virtual Path_Partner Path_Partner { get; set; }
    }
}
