//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path_Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Path_Partner()
        {
            this.Path_Partner_Parcel = new HashSet<Path_Partner_Parcel>();
            this.Path_Partner1 = new HashSet<Path_Partner>();
        }
    
        public long id { get; set; }
        public Nullable<long> partnerId { get; set; }
        public bool isFirst { get; set; }
        public Nullable<long> nextNode { get; set; }
        public long pathId { get; set; }
        public long areaId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Path Path { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Path_Partner_Parcel> Path_Partner_Parcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Path_Partner> Path_Partner1 { get; set; }
        public virtual Path_Partner Path_Partner2 { get; set; }
    }
}
