//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASC2023_PH_DesktopEntities : DbContext
    {
        public ASC2023_PH_DesktopEntities()
            : base("name=ASC2023_PH_DesktopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<roomtype> roomtypes { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
