//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> RoomType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public Nullable<byte> Availability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        public virtual roomtype roomtype1 { get; set; }
    }
}
